description="Push updates to the GAS project using clasp and redeploy the active deployment using the provided deployment ID."
prompt = """
You must run the following clasp commands in order to push local changes to Google Apps Script:
1. clasp push --force

2. clasp deploy -i AKfycbysuzeYXwPQXSCK0uO3gOR4q0mXmZJGLU35iUGEJ4pgtOD5_BQZ3Q-OaKWVDTbxQQi2
"""